language: node_js
node_js:
    - iojs
    - "4"
    - "5"
    - "6"
script: npm test
notifications:
    email:
        recipients:
            - zlatkofedor@cherryprojects.com
        on_success: change
        on_failure: always
